### ISSUE TITLE
where do I place the config?

### ISSUE THREAD

**Issue by dannyvoid** [Nekmo/amazon-dash#1]
Sorry if I'm missing something, but I don't see where to place the config file?

**Comment by dannyvoid** [comment]
... I should have tried running it first. I figured it out. Apologies.

**Comment by LimeBlast** [comment]
@dannyvoid if you don't mind my asking, how did you solve this? It would be handy for myself, and anyone else, that's suffering from this problem.

For my own part, I was able to run the `sudo amazon-dash run` command from the same directory as the `amazon-dash.yml` file, which made it run, but I'm interested in knowing if it's possible to pass the path to the config file via a parameter or something.

**Comment by Nekmo** [comment]
The parameter to define the configuration is `--config`. Go to #4.

**Comment by LimeBlast** [comment]
Hi, thank you for your reply. I did find the `--config` option, but was unable to make it work, no doubt my fault. 

I'm away for the rest of the weekend, but I'll take another look at this, and #4, on Tuesday. 

Thank you.

**Comment by Nekmo** [comment]
Please, write me the error that gives you.
