### ISSUE TITLE
How to use the "access_token" option

### ISSUE THREAD

**Issue by msanchezt** [Nekmo/amazon-dash#103]
Hi,

Anyone can point out how to use the "access_token" option for running commands in Home Assistant?

Thanks.

**Comment by msanchezt** [comment]
That didn't worked for me. Not clear what the "event" mean, as what I wanted is to trigger "services" (/api/services/) instead of events (/api/events).

I end up using this the API approach:

```
 ## Example of how to execute a url
#  AC:63:BE:67:B2:F1:
#    name: Kit Kat
#    url: 'http://domain.com/path/to/webhook'  # Url to execute
#    method: post  # HTTP method. By default GET
#    headers: {"authorization": "key"}
#    content-type: json  # Only available if Body is defined
#    body: '{"mac": "AC:63:BE:67:B2:F1", "action": "toggleLight"}'  # Request payload. Remember the quotes
```

**Comment by Nekmo** [comment]
You can run a service using an event in Home Assistant.

![43993264-eb447278-9d8a-11e8-9b90-81f5a736eaef](https://user-images.githubusercontent.com/740106/47621906-77b99700-dafe-11e8-95e4-a3782c694d6d.png)

You have info about events in the homeassistant documentation:
https://www.home-assistant.io/docs/configuration/events/
https://www.home-assistant.io/docs/automation/trigger/

You can use any event name. Just use an event name in amazon-dash and create an automation in Homeassistant for your event.

**Comment by WagnerBeccard** [comment]
Thourght on creating a new Issue for this but I think Its on topic. 
Just trying to get rid of the old API password myself and while I`m on it moveing Amazon-Dash from the Home assistant pi. 
My proposal would be:
bring back Home Assistant Rest API support 
i guess Cant even get the old buttons working - only getting 403 

Creating a event and useing it as a trigger for an automation is in my opinon doing things in a roundabout way.

**Comment by Nekmo** [comment]
Amazon-dash has never had support for other methods of the Home Assistant API than events. Maybe you're referring to the url executor:

http://docs.nekmo.org/amazon-dash/config_file.html#call-url

You can use this execution method if you prefer.

**Comment by WagnerBeccard** [comment]
Jea, maybe. But its quite strange

Working on the Home assistant PI v1.2.0

```
  aa:bb:cc:
    name: Durex Timer 10
    url: 'http://localhost:8123/api/services/script/turn_on'
    method: post
    headers: {"x-ha-access": "oldAPIpwd"}
    content-type: json
    body: '{"entity_id": "script.10min"}'
```
But not working on the seccond pi v1.3.1 
```
  aa:bb:cc:
    name: Durex Timer 10
    url: 'http://10.0.0.27:8123/api/services/script/turn_on'
    method: POST
    headers: {"x-ha-access": "oldAPIpwd"}
    content-type: json
    body: '{"entity_id": "script.10min"}'
```

**Comment by Nekmo** [comment]
I have tried to execute your command with both versions.

Amazon-dash v1.3.1:
```
POST /api/services/script/turn_on HTTP/1.1
Host: 127.0.0.1:8123
User-Agent: python-requests/2.18.4
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
x-ha-access: oldAPIpwd
content-type: application/json
Content-Length: 29

{"entity_id": "script.10min"}
```

Amazon-dash v1.2.0:
```
POST /api/services/script/turn_on HTTP/1.1
Host: 127.0.0.1:8123
User-Agent: python-requests/2.18.4
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
x-ha-access: oldAPIpwd
content-type: application/json
Content-Length: 29

{"entity_id": "script.10min"}
```

Both requests are exactly the same.

**Comment by Nekmo** [comment]
Closed due to inactivity.
