### ISSUE TITLE
Restrict to single interface

### ISSUE THREAD

**Issue by ekkesa** [Nekmo/amazon-dash#110]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

#### Description

Is it possible to restrict sniffing to a single interface? - E.g. only sniff on wlan0.

I believe this will free up a lot of CPU.

When starting up with defaults I see it puts eth0, wlan0 and lo into promiscuous mode.

**Comment by Nekmo** [comment]
Yes, you can use the interface option. It is not documented but the option exists.

```
(amazon-dash) [nekmo@homura ~/Workspace/amazon-dash] (develop)$ amazon-dash discovery --help
Welcome to Amazon-dash v1.3.1 using Python 3.6.6
Usage: amazon-dash discovery [OPTIONS]

  Discover Amazon Dash device on network.

Options:
  --interface TEXT  Network interface.
  --help            Show this message and exit.
```

It should also be available in the configuration file:

```
# amazon-dash.yml
# ---------------
settings:
  delay: 10
  interface: wlan0
```

**Comment by mcgurdan** [comment]
I don’t get the interface option and the config fails if added for me. Running amazon-dash version 1.3.1 python 2.7.9

**Comment by Nekmo** [comment]
Please paste the error and your configuration file. Thanks.

**Comment by Nekmo** [comment]
Closed due to inactivity.
