### ISSUE TITLE
First press does not work

### ISSUE THREAD

**Issue by mcgurdan** [Nekmo/amazon-dash#114]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version:
* Python version:
* Pip & Setuptools version:
* Operating System:

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [ ] The `pip install` or `setup install` command has been completed without errors
- [ ] The `python -m amazon_dash.install` command has been completed without errors
- [ ] The `amazon-dash discovery` command works without errors
- [ ] I have created/edited the configuration file
- [ ] *Amazon-dash service* or `amazon-dash --debug 

I was wondering if anyone else has noticed a bug in which the first press of the button of each day does not work. Instead I receive an email regarding choosing a product from Amazon Replenishment. After that it works fine, then I’ll see the issue again the next day..

Thoughts?

**Comment by Nekmo** [comment]
Does discovery work with the first execution of the day?

**Comment by mcgurdan** [comment]
I’ll check tomorrow

**Comment by mcgurdan** [comment]
Discovery does work. It almost seems like the wireless interface goes to sleep after a certain amount of time and then wakes up after the initial ARP request (but that one is not processed)

**Comment by Nekmo** [comment]
Some Wifi cards can enter energy saving mode. Maybe the drivers allow to disable this option.
https://unix.stackexchange.com/questions/269661/how-to-turn-off-wireless-power-management-permanently

Another option is to use ethernet cable. It will always be more stable.

**Comment by mcgurdan** [comment]
Been noticing this again. I’ll attempt the driver approach.

**Comment by mcgurdan** [comment]
Surprised no one else gets this issue. I have this now running off eth0 and still get the same issue. First press of the day results in an email from Amazon (please complete setup for dash button). Subsequent presses work fine.

**Comment by Nekmo** [comment]
Thanks for your answer :)

Regards,
