### ISSUE TITLE
Trouble installing on os x

### ISSUE THREAD

**Issue by Vernal** [Nekmo/amazon-dash#117]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version: ~
* Python version: 2.7.10
* Pip & Setuptools version: 18.1, 18.5
* Operating System: Mac high sierra 10.13.6

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [x ] The `pip install` or `setup install` command has been completed without errors
- [ ] The `python -m amazon_dash.install` command has been completed without errors
- [ ] The `amazon-dash discovery` command works without errors
- [ ] I have created/edited the configuration file
- [ ] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

I'm having trouble installing. Maybe someone has gotten past this. When running _sudo python -m amazon.dash install_ things fail. Immediately I get a ps: illegal option error:

> Executing all install scripts for Amazon-Dash
> [OK] config has been installed successfully
> ps: illegal option -- -
> usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
>           [-g grp[,grp...]] [-u [uid,uid...]]
>           [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
>        ps [-L]
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/Users/jason/Library/Python/2.7/lib/python/site-packages/amazon_dash/install/__main__.py", line 3, in <module>
>     catch(cli)()
>   File "/Users/jason/Library/Python/2.7/lib/python/site-packages/amazon_dash/install/__init__.py", line 47, in wrap
>     return fn(*args, **kwargs)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Library/Python/2.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/jason/Library/Python/2.7/lib/python/site-packages/amazon_dash/install/__init__.py", line 152, in all
>     has_service = has_service or (service().install() and
>   File "/Users/jason/Library/Python/2.7/lib/python/site-packages/amazon_dash/install/__init__.py", line 71, in install
>     self.is_installable()
>   File "/Users/jason/Library/Python/2.7/lib/python/site-packages/amazon_dash/install/__init__.py", line 107, in is_installable
>     if get_init_system() != 'systemd' or not get_systemd_services_path():
>   File "/Users/jason/Library/Python/2.7/lib/python/site-packages/amazon_dash/install/__init__.py", line 30, in get_init_system
>     return check_output(['ps', '--no-headers', '-o', 'comm', '1']).strip(b'\n ').decode('utf-8')
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['ps', '--no-headers', '-o', 'comm', '1']' returned non-zero exit status 1
>

**Comment by tduane** [comment]
removing '--no-headers' as an argument for the ps command in the __init__.py file resolved this error for me.

**Comment by Nekmo** [comment]
Solved in the development version.
