### ISSUE TITLE
Problem with home assistant event

### ISSUE THREAD

**Issue by juancarloscastro75** [Nekmo/amazon-dash#121]
Hi,
greetings from Spain.
I am trying to use your code with home assistant, but it does not work for me.

My information:
*** amazon-dash --version ***
You are running Amazon-dash v1.3.2 using Python 3.6.7.
This is the latest release
Installation path: /usr/local/lib/python3.6/dist-packages/amazon_dash
Current path: /home/home-server

*** python --version ***
Python 2.7.15rc1

*** pip --version ***
No se ha encontrado la orden «pip», pero se puede instalar con:

*** pip3 --version ***
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

*** easy_install --version ***
easy_install: orden no encontrada

*** sudo systemctl status  amazon-dash ***
● amazon-dash.service - Amazon Dash service
   Loaded: loaded (/usr/lib/systemd/system/amazon-dash.service; enabled; vendor 
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-01-29 10
  Process: 2791 ExecStart=/usr/bin/env amazon-dash run --config /etc/amazon-dash
 Main PID: 2791 (code=exited, status=4)

ene 29 10:20:10 home-server systemd[1]: amazon-dash.service: Main process exited
ene 29 10:20:10 home-server systemd[1]: amazon-dash.service: Failed with result 
lines 1-8/8 (END)...skipping...
● amazon-dash.service - Amazon Dash service
   Loaded: loaded (/usr/lib/systemd/system/amazon-dash.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-01-29 10:20:10 CET; 2s ago
  Process: 2791 ExecStart=/usr/bin/env amazon-dash run --config /etc/amazon-dash.yml (code=exited, status=4)
 Main PID: 2791 (code=exited, status=4)

ene 29 10:20:10 home-server systemd[1]: amazon-dash.service: Main process exited, code=exited, status=4/NOPERMISSION
ene 29 10:20:10 home-server systemd[1]: amazon-dash.service: Failed with result 'exit-code'.

If I chek the dash with "sudo amazon-dash discovery" I can see the dash, but later it does not call the service.

My amazon-dash.yml file:
`# amazon-dash.yml
# ---------------
settings:
  delay: 10
devices:
  00:FC:8B:DD:7C:E3:  
    name: Nescafe button
    homeassistant: 192.168.x.x
    event: dash1`

And the event from home assistant:
`automation:
  - alias: dash1
    trigger:
      - platform: event
        event_type: dash1
    action:
      service: light.turn_on
      entity_id: light.gateway_light_xxxxxxx`

Saludos y gracias

**Comment by juancarloscastro75** [comment]
Hi,
I think the names are OK : "dash1"

**Comment by Nekmo** [comment]
@juancarloscastro75, maybe your configuration is incorrect. You can test your configuration: http://docs.nekmo.org/amazon-dash/usage.html#check-config

@gt2416, there's probably a problem in your network. Amazon-dash and your button must be in the same network.

**Comment by juancarloscastro75** [comment]
OK thanks

The problem was on the permisions:
`Welcome to Amazon-dash v1.3.2 using Python 3.6.7
[Error] Amazon Dash Exception (SecurityException):
There should be no permissions for other users in the file "/etc/amazon-dash.yml". Current permissions: root:root 438. Only root must be able to write to file. Run "sudo chmod 660 '/etc/amazon-dash.yml' && sudo chown root:root '/etc/amazon-dash.yml'"`

And now, later of correct the permisions:
`Welcome to Amazon-dash v1.3.2 using Python 3.6.7
The configuration file "/etc/amazon-dash.yml" is correct`

And if I try to test device manually, no errors 👍 
`sudo amazon-dash test-device 00:FC:xx:xx:xx:xx --config /etc/amazon-dash.yml
Welcome to Amazon-dash v1.3.2 using Python 3.6.7
2019-02-03 09:36:38,246 - amazon-dash - INFO    - {"message": "Event dash1 fired."}`

**MUCHÍSIMAS GRACIAS**

Now the problem is on HA, that the event don't start

**Comment by Nekmo** [comment]
Me alegro que se haya solucionado :)

I close the issue

**Comment by juancarloscastro75** [comment]
Hi,

I'm using now a SSL conexion, and the dash has stopped working



home-server@home-server:~$ sudo amazon-dash test-device 00:FC:xx:xx:xx:xx --config /etc/amazon-dash.yml
Welcome to Amazon-dash v1.3.2 using Python 3.6.7
[Error] Amazon Dash Exception (ExecuteError):
Exception on request to **http**://192.168.3.10:8123/api/events/dash1: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

It is clear that the problem is in the type of connection.
I have verified the documentation, but I do not see how it works:

> **access**: Home Assistant legacy API password (x-ha-access header).
**verify**: By default True. Validate SSL/TLS certificate on request. To ignore errors (for example self-signed certificate) put false. You can also set the path to the certificate or certificate directory (generate using OpenSSL c_rehash utility). This can be useful if you use self-signed https.

Thans
