### ISSUE TITLE
amazon dash exception 401

### ISSUE THREAD

**Issue by ssevans87** [Nekmo/amazon-dash#123]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

I have set up everything and adjusted my config file to trigger an ifttt event. when i test the trigger i get "[error] Amazon Dash Exception (ExecuteError): "https..." return code 401"

The https is formatted exactly as it should be. I have checked the config file and it passes the test. Any suggestions on a fix would be appreciated.

**Comment by Nekmo** [comment]
Maybe you are using a expired or invalid token:

https://platform.ifttt.com/docs/api_reference

**Comment by Nekmo** [comment]
Closed due to inactivity.
