### ISSUE TITLE
New dash buttons and all have same MAC address?

### ISSUE THREAD

**Issue by KonttiAntti** [Nekmo/amazon-dash#124]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [X] Other

#### Description

I bought bunch of Amazon Dash buttons half a year ago. I'm frequently using many of them for many months without any issues. Now I tried to start using new buttons, and did everything same way, but Discovery don't find buttons and all 3 buttons show up with same MAC address.
I guess Amazon has changed configuration. Old buttons still work like a charm.

#### What I Did

```
After pressing dash button two new Macs appear :
sudo amazon-dash discovery
2c:4d:54:6c:50:4f (Amazon Device)
00:04:20:fa:f7:f8
I added 2c:4d:54 to discovery.py so that's why it says Amazon device. Same MACs for all three different buttons.
```

**Comment by Nekmo** [comment]
I've been searching for more similar cases and I have not found anything.

This could be a great Amazon method to prevent this project from working, but it could cause problems on most routers if two buttons are pressed at the same time.

**Comment by Nekmo** [comment]
Closed due to inactivity.
