### ISSUE TITLE
Command On Button Press Does Not Work In Combination With Docker

### ISSUE THREAD

**Issue by ploth** [Nekmo/amazon-dash#128]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with amazon-dash)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports

* amazon-dash version: master
* Python version: 3.7 (Docker)
* Pip & Setuptools version: not relevant
* Operating System: Docker (alpine)

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

Dockerfile uses Alpine Linux which has no support for bash. 

```
Error executing the device Button: Error running command /usr/bin/env bash -c echo test: The error code 127 has returned. Stderr: env: can't execute 'bash': No such file or directory
```

Error stack:

https://github.com/Nekmo/amazon-dash/blob/develop/amazon_dash/execute.py#L36
results in `/usr/bin/env bash`

because bash is the default shell here
https://github.com/Nekmo/amazon-dash/blob/develop/amazon_dash/execute.py#L39

and here is no shell name provided if you want to execute a command with your dash button
https://github.com/Nekmo/amazon-dash/blob/develop/amazon_dash/execute.py#L169

**Comment by Nekmo** [comment]
Bash will be added to the dockerfile, thanks!

https://www.cyberciti.biz/faq/alpine-linux-install-bash-using-apk-command/

**Comment by ploth** [comment]
Would be the easiest fix, yes :)

**Comment by ploth** [comment]
It would be nice if you can push a new PyPi package too. Thanks :)

**Comment by Nekmo** [comment]
Yes, it will be included in the next release, thanks :+1:
