### ISSUE TITLE
Having issues when checking the config

### ISSUE THREAD

**Issue by XzavierDunn** [Nekmo/amazon-dash#131]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

#### Description

After changing the amazon-dash.yml file and relocking it. It prints out
"Check the file and read the documentation. while scanning for the next token
found character '\t' that cannot start any token"

#### What I Did

This is whats in the .yml-

settings: 
    delay: 10
devices:
    my mac:
           name: button
           user: xd
           cmd: python3 hello.py

For now i'm just trying to keep it simple and get it working before I apply it to anything bigger.
After saving this and running - 
sudo chmod 600 amazon-dash.yml
sudo chown root:root amazon-dash.yml

I tried to do sudo amazon-dash check-config --config /etc/amazon-dash.yml then this popped up
"The configuration file is invalid (/etc/amazon-dash.yml). Check the file and read the documentation. 
While scanning for the next token found character '\t' that cannot start any token.

**Comment by Nekmo** [comment]
The character "\t" is the tab character. Try removing unnecessary tabulations in your configuration file.

**Comment by Nekmo** [comment]
Closed due to inactivity.
