### ISSUE TITLE
Systemd service does not work after reboot

### ISSUE THREAD

**Issue by scharrin2** [Nekmo/amazon-dash#132]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version: v1.3.2
* Python version: 2.7.13
* Pip & Setuptools version: pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
* Operating System: Raspbian GNU/Linux 9 (stretch)

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

I setup the autostart Smith the commands
sudo systemctl start amazon-dash

After a reboot I can see that the amazon-dash is running

pi@servberry:~ $ sudo systemctl status amazon-dash
● amazon-dash.service - Amazon Dash service
   Loaded: loaded (/lib/systemd/system/amazon-dash.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-03-06 19:40:31 CET; 1min 2s ago
 Main PID: 330 (amazon-dash)
   CGroup: /system.slice/amazon-dash.service
           └─330 /usr/bin/python /usr/local/bin/amazon-dash run --config /etc/amazon-dash.yml

Mar 06 19:40:31 servberry systemd[1]: Started Amazon Dash service.
Mar 06 19:40:32 servberry env[330]: Welcome to Amazon-dash v1.3.2 using Python 2.7.13
Mar 06 19:40:32 servberry env[330]: Listening for events. Amazon-dash will execute the events associated with the r
lines 1-10/10 (END)

But when I press the button on the Dash button, nothing happens.

#### What I Did

When restarting the amazon-dash with the command 

sudo systemctl restart amazon-dash

the Dash-Button works

**Comment by Nekmo** [comment]
Maybe amazon-dash should wait for the network to be available to start. Include this in your `amazon-dash.service`:

```
After=network-online.target
Wants=network-online.target
```

And reload daemons:
```
systemctl daemon-reload
```

**Comment by scharrin2** [comment]
Yes - now it works.

I put the two lines in the [Unit] section:

```
[Unit]
Description=Amazon Dash service
After=network-online.target
Wants=network-online.target

[Service]
User=root
ExecStart=/usr/bin/env amazon-dash run --config /etc/amazon-dash.yml
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

Best regards,
Christian

**Comment by Nekmo** [comment]
Thanks :) I will add this change to the next release.
