### ISSUE TITLE
On their verge of running correctly but...

### ISSUE THREAD

**Issue by XzavierDunn** [Nekmo/amazon-dash#134]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x ] Other

#### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I got to the very end of the process the config file was good and the tests were working but when it came to actually firing the button it wasn’t working and it was running as root and the user. I’m not even sure where to go from here.

**Comment by Nekmo** [comment]
Hello, discovery command works fine?

**Comment by XzavierDunn** [comment]
Yes! That works perfectly. I even ran wireshark and double checked it.

**Comment by XzavierDunn** [comment]
I don't know what changed but I reinstalled everything and it decided to work.

**Comment by Nekmo** [comment]
Maybe it was a temporary network issue. If you want, I can close the issue.

**Comment by XzavierDunn** [comment]
Yeah that's fine! I have no idea what was wrong before. My best advise for raspberry pi people though is to just nuke everything and reinstall the os if you run into bigger issues lmao
