### ISSUE TITLE
Amazon Dash Buttons disabled on purpose by Amazon?

### ISSUE THREAD

**Issue by puppinoo** [Nekmo/amazon-dash#136]
Hi,
I had 2 abandoned buttons in a drawer so I decided to reuse them with some IOT project.
Unfortunately after a few tests (they worked perfectly) now they seem to be disabled.
After the click one of them blinks red 3 times and then goes solid blue.
The other goes directly solid blue.
I tried to sniff traffic using tcpdump ether host <Known button MAC> but at the click I see no traffic anymore.
Tried to unregister and register again. Stuill same led patterns and no traffic.
Is this kind of protection known or buttons are simply broken or maybe I'm doing something stupid?

Thanks for any help.
Pino.

**Comment by Nekmo** [comment]
Several red blinks are normal if you have blocked your buttons on the router. Maybe you are not sniffing the network traffic correctly, or there is a problem on the network. It is always better to have the computer connected by a ethernet cable.

Regards,
Nekmo.

**Comment by puppinoo** [comment]
You were absolutely right!
Basically my 2.4 ssid on my LEDE router had an option called WMM enabled ([PRO-TIP to tuya and similar owners testing on OpenWRT / LEDE FW]: ALWAYS disable this option on 2.4ghz ssid before you try registration!). It always gave issues with alll IOT registrations (tuya etc etc). I disabled the option and the buttons reset correctly.
I thank you so much for the tip.

Pino.

**Comment by Nekmo** [comment]
Thanks for commenting how you have fixed it. It will be helpful for other OpenWRT users :)

Regards
