### ISSUE TITLE
Multiple URL execution

### ISSUE THREAD

**Issue by QuiGonLeong** [Nekmo/amazon-dash#137]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Can a single device perform a URL execution for 2 URLs? I need to it to post 2 different URLs with one device press.

**Comment by Nekmo** [comment]
You can execute a system command that executes the 2 urls with curl. At the moment this feature is not available in Amazon-dash.
