### ISSUE TITLE
Script output on journalctl

### ISSUE THREAD

**Issue by nitantsoni** [Nekmo/amazon-dash#138]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

#### Description

I was just wondering if there is a way to send the output of a bash script, as specified in the "cmd" field in the config file, to `journalctl`, under the `amazon-dash _SYSTEMD_UNIT`

I do have it working with the `logger` command, but then `journalctl -r -u amazon-dash` doesn't show them. They instead show up by running just `journalctl`

**Comment by Nekmo** [comment]
I think it's not possible, I'm sorry:
https://unix.stackexchange.com/questions/170469/how-to-direct-the-journal-output-of-certain-units-to-a-particular-file

But you can use rsyslog and then write to files (on the same or another machine).

Sorry for the delay!

**Comment by nitantsoni** [comment]
Thanks for checking on this! 👍
