### ISSUE TITLE
Not working on Raspberry pi?

### ISSUE THREAD

**Issue by 172pilot** [Nekmo/amazon-dash#14]
Sorry if this isn't the place for this but I can't find a forum.  When trying to run on a fresh install of current Raspbian, which has  Python 2.7 and 3.5.3 installed, I get to the point where I run the discovery and get:

pi@pi0w:~ $ sudo amazon-dash discovery
sudo: unable to resolve host pi0w
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    from amazon_dash.management import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 9, in <module>
    from amazon_dash.exceptions import AmazonDashException
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/exceptions.py", line 12, in <module>
    class ConfigFileNotFoundError(AmazonDashException, FileNotFoundError):
NameError: name 'FileNotFoundError' is not defined

To try to force it to use Python3, I changed the first line of /usr/local/bin/amazon-dash to point to python3 instead of just python, as a test, and I get slightly different error:

pi@pi0w:~ $ sudo amazon-dash discovery
sudo: unable to resolve host pi0w
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    from amazon_dash.management import execute_from_command_line
ImportError: No module named 'amazon_dash'

I know I must be missing something really stupid, but dont know where to go from here.  I can't be the only one trying to do this on RaspPi ZeroW, so hoping you may know.

Thanks for sharing your work.. I look forward to using this!!
-Steve

**Comment by Nekmo** [comment]
The first error seems to be a bug. I'm going to check that the tests for Python 2.7 are working well. Sorry for the inconvenience.

The second error, seems to be a problem for having done the installation first in Python 2.7, and later with Python 3.5. This is a Python problem.

This program should work without problems with a raspberry pi. I will check what happened. Thanks for the advice.

**Comment by Nekmo** [comment]
There is a new version that solves the problem (v0.3.1). Thanks for the report and happy 2018!
