### ISSUE TITLE
Question Telegram editing message

### ISSUE THREAD

**Issue by Metus88** [Nekmo/amazon-dash#142]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

Thanks for the tool! It's great!
I have only a question about telegram. It works, but the message that I receive when I press the button is:
`{"message":"Event dash_pressed fired."}`

Is it possible to change the message? ( example delating { , " , message  )
Where I can do it? Wich file I have to edit?
It isn't important. I can use telegram inside home assistant, but it was a curiosity and I will like to use telegram inside your tool.

#### What I Did
This is how set the telegram part on the amazon-dash.yml
```
confirmations:
  send-tg:
   service: telegram
   token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX' 
   to: XXXXXXXXXXXXXX
   is_default: true
```
Thanks a lot for your job! (And don't worry about my question... it's curiosity only)

**Comment by Nekmo** [comment]
Hi there! Sorry for the waiting. The message used with Telegram comes from the execution of your action. When Home Assistant executes the event, it returns the message to send to Telegram on Amazon-dash.

There is currently no way to change this message except in Home Assistant. I am developing a new version of Amazon-dash with many more options (including this one).
