### ISSUE TITLE
"Unable to init server: Could not connect: Connection refused" Issue

### ISSUE THREAD

**Issue by elwoodjd** [Nekmo/amazon-dash#146]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

- [X] The `pip install` or `setup install` command has been completed without errors
- [X] The `python -m amazon_dash.install` command has been completed without errors
- [X] The `amazon-dash discovery` command works without errors
- [X] I have created/edited the configuration file
- [X] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

I am just trying to get the service to actually see the button press.  I have installed everything on a fresh rasperry pi running the latest raspian OS; I am using the latest master release of amazon dash.  I also installed tcpdump as per the installation instruction.  I installed everything without errors.  When I run the discovery command, it gives me the MAC address (which I independently verified via WireShark).

However, when I execute it to run the daemon, nothing readily happens.  When I run the status command, I get the below

> pi@raspberrypi:/etc $ sudo systemctl start amazon-dash
> pi@raspberrypi:/etc $ sudo systemctl status amazon-dash
> ● amazon-dash.service - Amazon Dash service
>    Loaded: loaded (/usr/lib/systemd/system/amazon-dash.service; disabled; vendor preset: enabled)
>    Active: active (running) since Fri 2019-09-27 16:04:43 EDT; 7s ago
>  Main PID: 1577 (amazon-dash)
>     Tasks: 1 (limit: 2200)
>    Memory: 38.9M
>    CGroup: /system.slice/amazon-dash.service
>            └─1577 /usr/bin/python3 /usr/local/bin/amazon-dash run --config /etc/amazon-dash.yml
> 
> Sep 27 16:04:43 raspberrypi systemd[1]: Started Amazon Dash service.
> Sep 27 16:04:43 raspberrypi env[1577]: Welcome to Amazon-dash v1.3.3 using Python 3.7.3
> Sep 27 16:04:44 raspberrypi env[1577]: Listening for events. Amazon-dash will execute the events associated with the registered buttons.
> Sep 27 16:04:49 raspberrypi env[1577]: Unable to init server: Could not connect: Connection refused
> Sep 27 16:04:49 raspberrypi env[1577]: Unable to init server: Could not connect: Connection refused
> Sep 27 16:04:49 raspberrypi amazon-dash[1577]: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
> Sep 27 16:04:49 raspberrypi amazon-dash[1577]: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
> 

If I attempt to test the MAC address manually with  the test device command, it gives the expected success response and says its triggering the event (in my case, an IFTTT command).  But IFTTT never receives any signal.

My best guess is that amazon-dash is not connecting the server properly when the daemon runs, and thus isn't seeing the real button press traffic or able to send the IFTTT command out when I test-fire the device through the command line.  But, then why does the discovery command work?

I'm a novice to the world of Pi and modern coding in general, but I understand the basics and coded when I was younger, use the terminal on OSX frequently for trivial things, so I feel like with the right direction I should be able to solve this.

Thank you in advance for any help you might be able to provide.

**Comment by Nekmo** [comment]
These are GTK errors. It's weird, because there are no graphic components in Amazon-dash. Try running amazon-dash in manual mode.

Also paste your configuration file.

**Comment by elwoodjd** [comment]
Hi thanks so much for getting back to me.  I have posted the config file at the bottom.  It's didn't delete much just tried to activate what I needed, so I could refer to it later for future tinkering with other services.

As for manual mode, could you provide me a little more instruction?  Sorry.  I tried to google how to use manual mode in linux/debian systems but what I found sounded just complicated enough I wanted to confirm what to do before making tweaks that would be more difficult to troubleshoot later if I did it wrong.

> # amazon-dash.yml
> # ---------------
> settings:
>   # On seconds. Minimum time that must pass between pulsations.
>   delay: 10
> 
> 
> devices:
>   ## Example of how to execute a system command
>   #74:75:48:81:0b:83:  # You can know the mac of your device with the discovery command
>   #  name: button1  # You can put the name you want
>   #  user: root  # System user. Necessary if it is executed as root
>   #  cmd: spotify  # Command to execute
> 
>   ## Example of how to execute a system command over SSH
> #  AC:63:BE:75:1B:6F:
> #    name: Tassimo
> #    cmd: door --open
> #    ssh: 192.168.1.23:2222
> 
>    ## Example of how to execute a url
> #  AC:63:BE:67:B2:F1:
> #    name: Kit Kat
> #    url: 'http://domain.com/path/to/webhook'  # Url to execute
> #    method: post  # HTTP method. By default GET
> #    headers: {"authorization": "key"}
> #    content-type: json  # Only available if Body is defined
> #    body: '{"mac": "AC:63:BE:67:B2:F1", "action": "toggleLight"}'  # Request payload. Remember the quotes
> 
>    ## Example of how to execute a Homeassistant event
> #  40:B4:CD:67:A2:E1:
> #    name: Fairy
> #    homeassistant: hassio.local  # Address to the hass server
> #    event: toggle_kitchen_light  # Event name to send
> 
>    ## Example of how to execute a Openhab event
> #  18:74:2E:87:01:F2:
> #    name: Doritos
> #    openhab: 192.168.1.140  # Address to the openhab server
> #    item: open_door  # Openhab item. Required
> #    state: "ON"  # item state to send. TOGGLE by default
> 
>   ## Example of how to execute a IFTTT Webhook event
>   74:75:48:81:0b:83:
>     name: button_pressed
>     ifttt: dt43S0s0RE3c3yzGk9z6io
>     event: button_pressed
> #    data: {"value1": "Pompadour button"}
> 
> ## Uncomment this for use confirmations
> # confirmations:
>    ## Example of how to send a Telegram confirmation on execution success or failure
> #  send-tg:  # Confirmation name. Set your own confirmation name
> #    service: telegram  # Confirmation service. Currently only Telegram
> #    token: '402642618:QwGDgiKE3LqdkNAtBkq0UEeBoDdpZYw8b4h'  # Telegram token. Get it from Botfather
> #    to: 24291592  # Your Telegram id. You can get it using @get_id_bot
> #    is_default: true  # Use by default this confirmation for all devices
> #  send-pb:
> #    service: pushbullet
> #    token: 'o.BbbPYjJizbPr2gSWgXGmqNTt6T9Rew51'
> #    is_default: false
> 
> # Need help? See the documentation:
> # http://docs.nekmo.org/amazon-dash/config_file.html
> 
> # If you still need help open a issue:
> # https://github.com/Nekmo/amazon-dash/issues
> 
> 
>

**Comment by danielherrington** [comment]
@elwoodjd Did you find a fix for this? Running into the same bug.

**Comment by Nekmo** [comment]
Closed due to inactivity.
