### ISSUE TITLE
Scapy update

### ISSUE THREAD

**Issue by gpotter2** [Nekmo/amazon-dash#147]
### What is the purpose of your *issue*?
- [x] Other

### Description

Scapy 2.4.3 is available, which solves the installation issues versions 2.4.1/2.4.2 had.

Note that Scapy 2.4.0 (which is currently pinned)  is vulnerable to https://github.com/secdev/scapy/security/advisories/GHSA-q5wg-mj9r-hp59, and is now more than a year old.

I'd encourage to update.

**Comment by Nekmo** [comment]
The update will be included in the next release. Thank you!
