### ISSUE TITLE
Sniffing to multiple interfaces

### ISSUE THREAD

**Issue by kanda-robotics** [Nekmo/amazon-dash#148]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

I'd like to use both eth0 and wlan0.
When I didn't set interface value at the config file, it looked like sniffing only eth0.
When I set interface value wlan0 at the config file, it sniffed only wlan0 of course.
Is there way to sniff both eth0 and wlan0?

FYI, Scapy can use like this. `sniff(iface=["eth1","eth2"],...`

**Comment by Nekmo** [comment]
This is an interesting feature :+1:

**Comment by Nekmo** [comment]
Added to milestone v1.5.0!

**Comment by Nekmo** [comment]
Now available in the development branch! :)
