### ISSUE TITLE
Add systemd service option

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/amazon-dash#16]

**Comment by Kallb123** [comment]
On my RaspberryPi, it got installed to /usr/local/bin/amazon-dash, so I had to update the systemd service.

**Comment by Kallb123** [comment]
It also seems that 

ExecStart=/usr/bin/amazon-dash --config /etc/amazon-dash.yml

in amazon-dash.service would require the run command at the end? Is that correct?

**Comment by Nekmo** [comment]
Hello! Thanks for your comment.

As you say, it is necessary to add run to the end of the line. This was an error of the configuration example. Already solved.
https://github.com/Nekmo/amazon-dash/blob/master/services/amazon-dash.service

The path to the binary can change between each linux distribution. For example, in Arch Linux _Pip_ install the scripts to ``/usr/bin``. A possible alternative could be to use `/usr/bin/env`:

```
[alarm@alarmpi ~]$ /usr/bin/env amazon-dash --help
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
usage: amazon-dash [-h] [--config CONFIG] [--warning] [--quiet] [--debug]
                   [--verbose]
                   {discovery,run} ...

Amazon Dash.

positional arguments:
  {discovery,run}
    discovery      Discover Amazon Dash device on network.
    run            Run server

optional arguments:
  -h, --help       show this help message and exit
  --config CONFIG  Path to config file.
  --warning        set logging to warning
  --quiet          set logging to ERROR
  --debug          set logging to DEBUG
  --verbose        set logging to COMM
```

**Comment by Nekmo** [comment]
New systemd installer on v0.4.0:

```
sudo python -m amazon_dash.install systemd
```
