### ISSUE TITLE
SSIDs containing blanks cannot be configured

### ISSUE THREAD

**Issue by leres** [Nekmo/amazon-dash#161]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version: develop/8185d56
* Python version: 3.8.2
* Pip & Setuptools version: pip 20.0.2, setuptools 45.2.0
* Operating System: Ubuntu Desktop 20.04

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description
I have dash buttons that are currently associated with one SSID (that contains a blank) and I'm trying to move one to a different SSID that also contains a blank.

One problem is that the wifi network search fails to find the network because the networks returned by ConfigureAmazonDash.get_networks_availables() have escaped values (e.g. My%20Network). I solved that by escaping the ssid used in the search and can see the parameters being sent to the button:
```
/downloads/?amzn_ssid=My+Network&amzn_pw=SimplePassword
```
but this doesn't work (the button flashes red when I attempt to use it). I tried using urllib.parse.quote() to do that parameter quoting:
```
/downloads/?amzn_ssid=My%20Network&amzn_pw=SimplePassword
```
but that fails as well.

#### What I Did

```
amazon-dash configure --ssid 'My Network' --password 'SimplePassword'
```

**Comment by Nekmo** [comment]
Fixed in PR #160, thanks!
