### ISSUE TITLE
Error running a command

### ISSUE THREAD

**Issue by rexian96** [Nekmo/amazon-dash#19]
Hi there, thanks for creating amazon-dash!

Wanted to give it a try and encountered the below error when the button is pressed -

root@DietPi:~# amazon-dash --config=amazon-dash.yml run
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 103, in execute_from_command_line
    execute_args(args)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 65, in execute_args
    Listener(args.config).run(root_allowed=args.root_allowed)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 72, in run
    scan_devices(self.on_push, lambda d: d.src.lower() in self.devices)
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/scan.py", line 12, in scan_devices
    except PermissionError:
NameError: global name 'PermissionError' is not defined

![image](https://user-images.githubusercontent.com/35205445/34656437-59af0108-f3e8-11e7-97c6-fbfe05403b1b.png)
[rishav.sh.txt](https://github.com/Nekmo/amazon-dash/files/1610408/rishav.sh.txt)
[amazon-dash.yml.txt](https://github.com/Nekmo/amazon-dash/files/1610409/amazon-dash.yml.txt)

**Comment by Nekmo** [comment]
Hello, thank you for using Amazon-dash :)

It seems that the tests do not cover that part of the code and there is a problem with Python 2.7. You can use Python3 in the meantime.

I will solve that problem today. Thanks for reporting.

**Comment by Nekmo** [comment]
It is already solved, sorry for the inconvenience.

In my house I only use Python 3 and that part was not covered by the tests. I've tried it with Python 2.7 and now it should work.

Remember to update the package to download the fixed version.

```
pip install amazon-dash -U
```

Thanks and happy new year.

**Comment by rexian96** [comment]
Thank YOU for taking care of it so quickly. I am getting a new error but that one is definitely resolved! I did have Python 3 but seems like 2.7 was the default.

root@DietPi:~# amazon-dash --config=amazon-dash.yml run
[Error] Amazon Dash Exception:
For security, execution as root is not allowed.

**Comment by Nekmo** [comment]
Add user to device section like this:

```
  50:F5:DA:06:4C:8F:
    name: Device name
    user: <your_user>
    cmd: <command to execute>
```

This is a security measure to avoid executing commands like root, which is dangerous. You can disable this security measure with: `--root-allowed`.

Have a nice day :)

**Comment by rexian96** [comment]
Thanks again. You too have a nice day!
