### ISSUE TITLE
How to call the API of Homeassistant with curl

### ISSUE THREAD

**Issue by conradhagemans** [Nekmo/amazon-dash#2]
I want to make an API call to Homeassistant once the button is pressed.

On the command line I would run:

curl -X POST -H "x-ha-access: MyPassword" -H "Content-Type: application/json" -d '{"entity_id": "light.livingroom"}' https://www.mydomain.com:8123/api/services/light/toggle

How to do this from within this nice script?
I created a bash script file with the name test. If I put that in as command in the config file a get errors like:

2017-03-11 02:12:53,609 - amazon-dash - ERROR   - 1 return code on "sudo -s --set-home -u myname /usr/bin/env bash -c test" command. Stderr: b''

How to fix this?

**Comment by Nekmo** [comment]
Create a bash script with your code:

```
#!/usr/bin/env bash
curl -X POST -H "x-ha-access: MyPassword" -H "Content-Type: application/json" -d '{"entity_id": "light.livingroom"}' https://www.mydomain.com:8123/api/services/light/toggle
```
Add execution permissions:
```
chmod +x myscript.sh
```

Add this to your settings file:
```settings:
  delay: 10
devices:
  0C:47:C9:98:4A:12:
    name: MyScript
    user: yourname
    cmd: /path/to/myscript.sh
```
Sorry for the delay.
