### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Kallb123** [Nekmo/amazon-dash#21]
Any chance of logging either to standard output or a file? Sorry if I've missed it but there doesn't seem to be any reference to logs.

If I check sudo systemctl status dash.service it just says that it started OK, but doesn't report anything. 

I'd like to see reports on button presses and commands sent. 

I'm struggling to figure out why my light isn't toggling when I press a dash button, home assistant isn't showing any MQTT messages, so I believe amazon-dash must not be doing anything. Whether it's picking up the button press or not is unknown unfortunately.

**Comment by Nekmo** [comment]
Press button events are a debug logger.
https://github.com/Nekmo/amazon-dash/blob/00000b6dee9fd8eb31e743d066b344b1b378720e/amazon_dash/listener.py

 You can change Amazon-dash to **debug mode** using parameter ``--debug``. This is not documented but surely it should be.

Greetings and thanks for your issue.
