### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by Kallb123** [Nekmo/amazon-dash#22]
What unit is the delay in? Seconds? Minutes?

I would guess at seconds, because the dash button seems to be active for just under that. Is there a minimum that we shouldn't go below? Does it take a certain amount of time for the button to drop off the network ready to be picked up again?

**Comment by Nekmo** [comment]
The delay is in seconds. It should be documented.

Forgive the inconvenience and thanks for your report.

**Comment by ubikapps** [comment]
So this must not be set to anything below 10 seconds?
