### ISSUE TITLE
Button not being detected using Wi-Fi extender

### ISSUE THREAD

**Issue by Kallb123** [Nekmo/amazon-dash#23]
Pressing my dash button doesn't seem to be noticed by amazon-dash. I have enabled debug logging and then run sudo systenctl status dash.service and there's nothing showing up. I get the amazon notification, so I know the button is working.

I've installed on a raspberry pi 3, which is also my network dns server and dhcp server, but not my gateway. Its connected via ethernet.

What further steps could I take to debug this issue?

**Comment by Kallb123** [comment]
I noticed that I had a WiFi extender very close to where the dash button is located. I unplugged it and the whole system seems to work flawlessly. Button press is detected and mqtt message is received by home assistant.

Unfortunately that means  alow signal at that end of the house. I tested it several times and it worked 4/4 times. I'm going to plug the extender back in, give it a while and then try it again.

**Comment by Nekmo** [comment]
Amazon-dash sniff all UDP packages on your RPI network:

https://github.com/Nekmo/amazon-dash/blob/master/amazon_dash/scan.py#L18

If your Wi-Fi extender does not forward those packets, Amazon-dash will not be able to detect the press event. Personally I do not use a Wifi extension, but even if I used a Wi-Fi extension, my extension model and yours probably work differently. I can not do the tests necessary to solve the problem.

You can try to change your network. For example, you can use your RPI as relay. You can try using Scapy yourself for detect other packages. Everything you discover can be integrated into the project.

Sorry for not being able to help more.

**Comment by Kallb123** [comment]
I'm not entirely sure how change the network and test it all unfortunately. I naively assume the packets must be passed on because the dash button connects to the Internet successfully (the app notifies me of the hutton press)

**Comment by Nekmo** [comment]
The wifi extension may be forwarding the TCP packets to the Amazon servers, but not the UDP packets announcing that the new device is on the network. You can test this on your RPI using Python3 console:

```
from scapy.all import *

sniff(prn=lambda x: print(x.src), lfilter=lambda d: d.src != '00:00:00:00:00:00')
```

Remember to run Python3 as root and have Scapy installed.

**Comment by Nekmo** [comment]
Closed due to inactivity. When there is news, it can be reopened.
