### ISSUE TITLE
Won't run on RPi 3

### ISSUE THREAD

**Issue by nukefrenzy** [Nekmo/amazon-dash#31]
* amazon-dash version: 0.4.1
* Python version: 2.7.13
* Operating System: RPi 3 running Raspbian Stretch

### Description

I followed the installation instructions and installed tcpdump as well.  However, I keep getting the error below and the program will not run.

### What I Did

pi@raspberrypi:~ $ amazon-dash --help
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    from amazon_dash.management import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 11, in <module>
    from amazon_dash.listener import Listener, test_device
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 8, in <module>
    from amazon_dash.scan import scan_devices
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/scan.py", line 6, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by Nekmo** [comment]
Try running the program as root. It is necessary to run Amazon-dash as root to be able to sniff packages on the network.

**Comment by nukefrenzy** [comment]
I tried running with sudo, but no difference.

**Comment by Nekmo** [comment]
Hello,

I have searched about your error, and it could be because you have installed scapy-python3 instead  scapy.

I have made an installation in Python 2 and I have not been able to reproduce the failure in the dependency:

 ```
[nekmo@homura ~]$ mktmpenv -p /usr/bin/python2
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/python2
Also creating executable in /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/preactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/postactivate
virtualenvwrapper.user_scripts creating /home/nekmo/.virtualenvs/tmp-7975d4959ec8110/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-7975d4959ec8110) [nekmo@homura ~/.virtualenvs/tmp-7975d4959ec8110]$ 
(tmp-7975d4959ec8110) [nekmo@homura ~/.virtualenvs/tmp-7975d4959ec8110]$ pip install amazon-dash
Collecting amazon-dash
  Downloading amazon-dash-0.4.1.post1.tar.gz
Collecting scapy (from amazon-dash)
Collecting PyYAML>=3.0 (from amazon-dash)
Collecting jsonschema (from amazon-dash)
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl
Collecting requests (from amazon-dash)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting click (from amazon-dash)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting click-default-group (from amazon-dash)
Collecting functools32; python_version == "2.7" (from jsonschema->amazon-dash)
Collecting certifi>=2017.4.17 (from requests->amazon-dash)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl                                                                                                                                                                                              
Collecting chardet<3.1.0,>=3.0.2 (from requests->amazon-dash)                                                                                                                                                                                      
  Using cached chardet-3.0.4-py2.py3-none-any.whl                                                                                                                                                                                                  
Collecting idna<2.7,>=2.5 (from requests->amazon-dash)                                                                                                                                                                                             
  Using cached idna-2.6-py2.py3-none-any.whl                                                                                                                                                                                                       
Collecting urllib3<1.23,>=1.21.1 (from requests->amazon-dash)                                                                                                                                                                                      
  Using cached urllib3-1.22-py2.py3-none-any.whl                                                                                                                                                                                                   
Building wheels for collected packages: amazon-dash                                                                                                                                                                                                
  Running setup.py bdist_wheel for amazon-dash ... done                                                                                                                                                                                            
  Stored in directory: /home/nekmo/.cache/pip/wheels/22/c4/c8/26fe5549926ad5419ee4e803e0ed0ce6d1cac52c411f2d812d                                                                                                                                   
Successfully built amazon-dash                                                                                                                                                                                                                     
Installing collected packages: scapy, PyYAML, functools32, jsonschema, certifi, chardet, idna, urllib3, requests, click, click-default-group, amazon-dash                                                                                          
Successfully installed PyYAML-3.12 amazon-dash-0.4.1.post1 certifi-2018.1.18 chardet-3.0.4 click-6.7 click-default-group-1.2 functools32-3.2.3.post2 idna-2.6 jsonschema-2.6.0 requests-2.18.4 scapy-2.3.3 urllib3-1.22                            
(tmp-7975d4959ec8110) [nekmo@homura ~/.virtualenvs/tmp-7975d4959ec8110]$ amazon-dash 
[Error] Amazon Dash Exception:                                                                                                                                                                                                                     
The configuration file was not found on "/home/nekmo/.virtualenvs/tmp-7975d4959ec8110/amazon-dash.yml"                                                                                                                                             
(tmp-7975d4959ec8110) [nekmo@homura ~/.virtualenvs/tmp-7975d4959ec8110]$ amazon-dash --help                                                                                                                                                        
usage: amazon-dash [-h] [--config CONFIG] [--warning] [--quiet] [--debug]                                                                                                                                                                          
                   [--verbose]                                                                                                                                                                                                                     
                   {discovery,check-config,test-device,run} ...                                                                                                                                                                                    
                                                                                                                                                                                                                                                   
Amazon Dash.

positional arguments:
  {discovery,check-config,test-device,run}
    discovery           Discover Amazon Dash device on network.
    check-config        Validate the configuration file.
    test-device         Test a configured device without press button.
    run                 Run server

optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG       Path to config file.
  --warning             set logging to warning
  --quiet               set logging to ERROR
  --debug               set logging to DEBUG
  --verbose             set logging to COMM
```

To confirm the problem, please execute:

    pip freeze

**Comment by nukefrenzy** [comment]
pi@raspberrypi:~ $ pip freeze
amazon-dash==0.4.1.post1
automationhat==0.0.4
blinker==1.3
blinkt==0.1.0
Cap1xxx==0.1.3
chardet==2.3.0
click==6.6
click-default-group==1.2
colorama==0.3.7
cryptography==1.7.1
drumhat==0.0.5
enum34==1.1.6
envirophat==0.0.6
ExplorerHAT==0.4.2
Flask==0.12.1
fourletterphat==0.0.2
functools32==3.2.3.post2
gpiozero==1.4.0
idna==2.2
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.8
jsonschema==2.6.0
keyring==10.1
keyrings.alt==1.3
lxkeymap==0.1
MarkupSafe==0.23
mcpi==0.1.1
microdotphat==0.1.3
mote==0.0.3
motephat==0.0.2
numpy==1.12.1
oauthlib==2.0.1
phatbeat==0.0.2
pianohat==0.0.5
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.38
Pillow==4.0.0
pyasn1==0.1.9
pycrypto==2.6.1
pygame==1.9.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.4.2
pyOpenSSL==16.2.0
pyserial==3.2.1
pyxdg==0.25
PyYAML==3.12
rainbowhat==0.0.2
requests==2.12.4
requests-oauthlib==0.7.0
RPi.GPIO==0.6.3
RTIMULib==7.2.1
scapy-python3==0.23
scrollphat==0.0.7
scrollphathd==1.1.1
SecretStorage==2.3.1
sense-emu==1.0
sense-hat==2.2.0
simplejson==3.10.0
six==1.10.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.3
touchphat==0.0.1
twython==3.4.0
urllib3==1.19.1
Werkzeug==0.11.15

**Comment by Nekmo** [comment]
I don't know why you have installed scapy-python3 on python2. Maybe this is installed by other package. Uninstall it (pip uninstall scapy-python3) and install scapy (pip install scapy)

**Comment by nukefrenzy** [comment]
That worked like a charm and I just received a text from IFTTT when I pushed my dash button!  Python comes preinstalled on Raspbian so it probably has something to do with that.  Thank you for your help!

**Comment by Nekmo** [comment]
You're welcome ;)

**Comment by sAnKeT-nAiK** [comment]
Thank you : )

**Comment by MrNerDD** [comment]
please help me to solve this problem mentioned below..
Traceback (most recent call last):
  File "/usr/bin/websploit", line 57, in <module>
    from modules import arp_poisoner
  File "/usr/share/websploit/modules/arp_poisoner.py", line 11, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by Nekmo** [comment]
@MrNerDD you have mistaken repository. Open a ticket in the correct project.

**Comment by MrNerDD** [comment]
> @MrNerDD you have mistaken repository. Open a ticket in the correct project.

there,s nothing wrong with my repository . i am using official repo by kali linux. this error coming with 3 other tools

**Comment by Nekmo** [comment]
@MrNerDD this is the amazon-dash project. It seems that you are using websploit. Please contact the websploit team.

**Comment by MrNerDD** [comment]
i know . i thought you know about it. nd yes this is websploit issue  .. anyway thanks

**Comment by Nekmo** [comment]
> I don't know why you have installed scapy-python3 on python2. Maybe this is installed by other package. Uninstall it (pip uninstall scapy-python3) and install scapy (pip install scapy)

Try It.
