### ISSUE TITLE
TypeError: 'errors' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by kikemakina** [Nekmo/amazon-dash#32]
* amazon-dash version: la última
* Python version: 2.7.13
* Operating System: raspbian stretch

### Description
Me da una serie de errores si intento ejecutar cualquier comando, son estos:
pi@HomeAssistant:~ $ amazon-dash --help
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    from amazon_dash.management import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 11, in <module>
    from amazon_dash.listener import Listener, test_device
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 8, in <module>
    from amazon_dash.scan import scan_devices
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/scan.py", line 6, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

### What I Did
No sé qué hacer
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Nekmo** [comment]
Buenas, creo que puede haberse realizado la instalación por wheel, y ha instalado un paquete incorrecto para scapy.

Ejecuta primero esto:

    pip uninstall scapy-python3

Y luego lo siguiente:

    pip install scapy

Estoy investigando lo ocurrido, perdona las molestias.

**Comment by kikemakina** [comment]
Tienes una raspberry para probar, ahora no tengo tiempo, mañana cargaré una copia de la sd y empezré de nuevo. Lo que me parece raro es que el servicio amazon-dash.service no lo pone en la ruta etc/systemd/system que es donde van por defecto

**Comment by Nekmo** [comment]
El error que tienes es el mismo que en este otro issue:
https://github.com/Nekmo/amazon-dash/issues/31

Instalando la dependencia correcta debería solucionarse el problema. Creo que el fallo puede que esté en la instalación cuando pip selecciona wheel como método de instalación. Acabo de lanzar una nueva release que deshabilita wheel.

Tengo una RPI B+, pero con Archlinux, no Debian. En mi instalación no he tenido este problema, pero cada sistema es un mundo y es mejor que lo pruebes por ti mismo.

En el issue que hago referencia, quien creó el caso también usaba Raspbian, y esta solución arregló el problema.

Si pruebas la solución cuéntame qué tal te va.

Un saludo.

**Comment by Nekmo** [comment]
He probado la instalación en Hassbian, que es la misma distro que Raspbian pero algo modificada, y con la última versión de Amazon-dash funciona. Con los siguientes comandos debería funcionar si tienes la versión anterior:

    sudo pip uninstall scapy-python3

Y después:

    sudo pip install --force-reinstall python3

Saludos.

**Comment by Nekmo** [comment]
Para ver el error, utiliza:

```journalctl -r -u amazon-dash```

Es posible que el problema esté en el archivo de configuración. Puedes probar la configuración con:

```amazon-dash --config /etc/amazon-dash.yml check-config```

El nombre del evento debes definirlo en Home Assistant y asociarlo con las acciones que quieres que se realicen.

Un saludo.

**Comment by kikemakina** [comment]
Bueno, te agradezco la atención prestada, pero no soy capaz de enlazarlo con el input_boolean de home assistant, así que lo dejo por imposible. Buscaré otras soluciones para poder usar el dash.

**Comment by Nekmo** [comment]
Con este programa también puedes ejecutar comandos o llamar a una url. Comprueba no obstante que el programa esté recibiendo el evento de pulsación. Para ello puedes usar el comando discovery.

**Comment by Nekmo** [comment]
Se cierra hilo debido a inactividad.
