### ISSUE TITLE
Raspberry install Failed

### ISSUE THREAD

**Issue by Marvv90** [Nekmo/amazon-dash#36]
* amazon-dash version:0.4.1
* Python version:3.5
* Operating System:Raspbian Jessi Lite

### Description

When I execute sudo python -m amazon_dash.install it fails with the text:
"/usr/bin/python: No module named amazon_dash"
"/usr/bin/python3.5: Error while finding module specification for 'amazon_dash.install' (ImportError: No module named 'amazon_dash')"
"/usr/bin/python3: Error while finding module specification for 'amazon_dash.install' (ImportError: No module named 'amazon_dash')"

### What I Did

Reinstall and install with pip3 install amazon-dash
Tried which all variant of python --> "python" / "python3" / "python3.5"

**Comment by Nekmo** [comment]
This error means that Amazon-dash is not installed. Uninstall amazon-dash using pip and reinstall it. Then paste the result here (I need to see the result of the installation process)

```
$ sudo pip3 uninstall amazon-dash
$ sudo pip3 install --no-cache-dir amazon-dash 
```

Also execute:

```
$ pip3 --version
```

**Comment by Nekmo** [comment]
Your problem may be due to having several versions of Python on your system or different environments. If your "Pip3" command is associated with Python 3.4 for example, it is normal that it does not work.

I can not give you a solution if I do not see in which folder Amazon-dash is installed.

I want to help you but I need your help to help you.

**Comment by Marko79** [comment]
pi@Pibroker:~ $ sudo pip3 uninstall amazon-dash
Cannot uninstall requirement amazon-dash, not installed
pi@Pibroker:~ $ sudo pip3 install --no-cache-dir
You must give at least one requirement to install (see "pip help install")
pi@Pibroker:~ $ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
pi@Pibroker:~ $ 

I have the same problem
Can u help to fix it?

**Comment by Nekmo** [comment]
About this output:
```
pi@Pibroker:~ $ sudo pip3 uninstall amazon-dash
Cannot uninstall requirement amazon-dash, not installed
```
Based on your results, you no longer have Amazon-dash installed in Python 3.5. If you can continue running amazon-dash on your system it means that you have it installed using another version of Python.

About:
```
pi@Pibroker:~ $ sudo pip3 install --no-cache-dir
You must give at least one requirement to install (see "pip help install")
```
Please do not forget the name of the package to be installed: `$ sudo pip3 install --no-cache-dir` **amazon-dash**

**Comment by Marko79** [comment]
$ ./iobroker url "https://github.com/Nekmo/amazon-dash"
install https://github.com/Nekmo/amazon-dash/tarball/master
npm install https://github.com/Nekmo/amazon-dash/tarball/master --production --prefix "/opt/iobroker" (System call)
npm ERR! Linux 4.9.59-v7+npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "https://github.com/Nekmo/amazon-dash/tarball/master" "--production" "--prefix" "/opt/iobroker"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10

npm ERR! path /tmp/npm-1295-f0ff4152/unpack-a6ebdef6/package.jsonnpm ERR! code ENOENT

npm ERR! errno -2npm ERR! syscall open


npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-1295-f0ff4152/unpack-a6ebdef6/package.json'npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-1295-f0ff4152/unpack-a6ebdef6/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

ERROR: host.Pibroker Cannot install https://github.com/Nekmo/amazon-dash/tarball/master: 254
ERROR: process exited with code 25


Tryed a couple things and now i get this...
any idea???

**Comment by Nekmo** [comment]
Please just execute:
```
sudo pip3 install --no-cache-dir amazon-dash
```
You forgot to write the last word the last time you tried. Please copy & paste the code to avoid making typos.

Npm is for Node (JS) packages. Amazon-dash is a Python package.

**Comment by Nekmo** [comment]
Closed by inactivity. Reopen on news.
