### ISSUE TITLE
Problem with "amazon-dash discovery" command on Raspbian Stretch

### ISSUE THREAD

**Issue by areknames96** [Nekmo/amazon-dash#39]
* amazon-dash version:0.4.1
* Python version:2.7
* Operating System:Raspbian Stretch

### Description
When I run "sudo amazon-dash discovery",
he gives me:
"pi@raspberrypi:~ $ sudo amazon-dash discovery
Traceback (most recent call last):
  File "/usr/local/bin/amazon-dash", line 6, in <module>
    from amazon_dash.management import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/management.py", line 11, in <module>
    from amazon_dash.listener import Listener, test_device
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/listener.py", line 8, in <module>
    from amazon_dash.scan import scan_devices
  File "/usr/local/lib/python2.7/dist-packages/amazon_dash/scan.py", line 6, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function"
How can I solve?

**Comment by Nekmo** [comment]
Upgrade It to Amazon-dash 0.4.2 or install Scapy package instead scapy-python3 

Regards :)

**Comment by areknames96** [comment]
Hello! Thanks for the quick answer.
Excuse me, I'm an IT specialist, but I still don't have much practicality with Linux. I followed the guide, I also followed your tips, and in fact now the discovery works. Now the problem is that I run sudo systemctl start amazon-dash, but by pressing the dash button nothing happens. My goal is to fire an event on ifttt with webhooks. I configured this way:

settings:
   delay: 1
devices:
   my_dash_button_mac:
    name: Button_Pressed
    url: 'https://maker.ifttt.com/trigger/buttonpressed/with/key/my_key'

Obviously the url to trigger the event on ifttt works, if I put it in the browser.
Would you have any idea what the problem might be?

**Comment by Nekmo** [comment]
Hi,

Check that the service is running correctly:
```
sudo systemctl status amazon-dash
```

And check your config file:
```
sudo amazon-dash --config /etc/amazon-dash.yml check-config
```

You can also try the execution without using your amazon-dash button:
```
sudo amazon-dash --config /etc/amazon-dash.yml test-device <device mac address>[ --root-allowed]
```

If you still have problems with the service you can try running Amazon-dash from a terminal:
```
sudo amazon-dash --config /etc/amazon-dash.yml run
```

Regards!

**Comment by areknames96** [comment]
Thank you! After a restart it worked

**Comment by Nekmo** [comment]
You're welcome :)
