### ISSUE TITLE
How can I send a trigger to a password-protected Home Assistant?

### ISSUE THREAD

**Issue by areknames96** [Nekmo/amazon-dash#42]
Hi, the guide explains how to trigger an event on home assistant, but it does not work if home assistant is password protected, how can I do?

**Comment by Nekmo** [comment]
Hello, there is already a issue about this.

**Comment by areknames96** [comment]
It works for urls and cmd, but I don't know how to modify for home assistant

**Comment by areknames96** [comment]
For example, if I have this:
" 00:00:00:00:00:00:
    name: switch
    homeassistant: 192.168.1.x:8123
    event: switch_event"
What line of code should I add to also insert the api_password?

**Comment by Nekmo** [comment]
This is currently unsupported on Home Assistant module, but you can use Url module for It.

https://github.com/Nekmo/amazon-dash/issues/37#issuecomment-368667643

The Amazon-dash release will include password-protected support in the Home Assistant module :)

**Comment by Nekmo** [comment]
This feature has been included in the development branch.
