### ISSUE TITLE
Troubleshooting my config on hassbian image 

### ISSUE THREAD

**Issue by WagnerBeccard** [Nekmo/amazon-dash#43]
* amazon-dash version: 1.0.1
* Python version:3.5.3
* Operating System: Hassbian  4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux

### Description

I try to get the buttons working for triggering lights, scripts and what ever for Home Assistant. 
Made a simple toogle witch is also working on the command line. but not, when i press the buttons. 

Funny thing is, yesterday eveining it worked one time, in a loop. Hadnt installed tcpdump (my own disco)
Now with tcpdump the discovery element dont show the button presses (Amazon device) but the 15 other connected devices.

Do i maybe have to set up a port forwarding in my router?? 
### What I Did

```
pi@hassbian:~ $ sudo systemctl status amazon-dash.service
● amazon-dash.service - Amazon Dash service
   Loaded: loaded (/lib/systemd/system/amazon-dash.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-04-13 10:21:10 CEST; 44s ago
 Main PID: 331 (amazon-dash)
   CGroup: /system.slice/amazon-dash.service
           └─331 /usr/bin/python3 /usr/local/bin/amazon-dash run --config /etc/amazon-dash.yml

Apr 13 10:21:10 hassbian systemd[1]: Started Amazon Dash service.
Apr 13 10:21:12 hassbian env[331]: Welcome to Amazon-dash v1.0.1 using Python 3.5.3
Apr 13 10:21:12 hassbian env[331]: Listening for events. Amazon-dash will execute the events associated with the registered buttons.
pi@hassbian:~ $ ps ax|grep dash
  331 ?        Ss     0:10 /usr/bin/python3 /usr/local/bin/amazon-dash run --config /etc/amazon-dash.yml
  759 pts/0    S+     0:00 grep --color=auto dash
pi@hassbian:~ $ sudo journalctl -r -u amazon-dash
-- Logs begin at Thu 2016-11-03 18:16:42 CET, end at Fri 2018-04-13 10:24:40 CEST. --
Apr 13 10:21:12 hassbian env[331]: Listening for events. Amazon-dash will execute the events associated with the registered buttons.
Apr 13 10:21:12 hassbian env[331]: Welcome to Amazon-dash v1.0.1 using Python 3.5.3
Apr 13 10:21:10 hassbian systemd[1]: Started Amazon Dash service.
pi@hassbian:~ $ sudo amazon-dash test-device 0c:47:c9:fc:7a:cb --config /etc/amazon-dash.yml
Welcome to Amazon-dash v1.0.1 using Python 3.5.3
pi@hassbian:~ $ pip freeze
amazon-dash==1.0.1
certifi==2018.1.18
chardet==3.0.4
click==6.7
click-default-group==1.2
cryptography==1.7.1
dnspython==1.15.0
enum34==1.1.6
functools32==3.2.3.post2
idna==2.6
ipaddress==1.0.17
jsonschema==2.6.0
keyring==10.1
keyrings.alt==1.3
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
RPi.GPIO==0.6.3
scapy-python3==0.23
SecretStorage==2.3.1
six==1.10.0
urllib3==1.22


```

Dash service installed via your installer, looks good
after trying around 4hrs im at the end of my ideas..

**Comment by Nekmo** [comment]
Hi, can you confirm that the buttons are on the same network as the router? Did the discovery command work to obtain the MAC address of the buttons?

Regards

**Comment by WagnerBeccard** [comment]
New advanced router is on the way. I already know this Huawai router witch i got from my ISP is poison. would still like to know what is going on. 

for others - a small list for Home Assistant calls

```
 SWITCH
# http://localhost:8123/api/services/switch/turn_on
LIGHT
# http://localhost:8123/api/services/light/toggle'
SCRIPT
# http://localhost:8123/api/services/script/turn_on
```
sample config: 

  ac:63:be:58:ff:33:
    name: coffetimer
    url: 'http://localhost:8123/api/services/script/turn_on'
    method: post
    headers: {"x-ha-access": "supersecrethttpapipwd"}
    content-type: json
    body: '{"entity_id": "script.the_coffe_timer"}'
