### ISSUE TITLE
Install Error 404 with pip3 command

### ISSUE THREAD

**Issue by djryan012** [Nekmo/amazon-dash#56]
* amazon-dash version: 1.1
* Python version: 3.5
* Operating System: hassbian on Pi3

### Description

trying to install using documents from the site but getting a lot of error messages
I tried using pip but got command not found because I have python 3... so I used pip3 and got the HTTP error 404 messages. Not sure if this is with my version of Hassbian or install error that I cant make sense of.

### What I Did
```
pi@hassbian:~ $ sudo pip3 install amazon-dash
Collecting amazon-dash
  Using cached https://www.piwheels.org/simple/amazon-dash/amazon_dash-1.0.4-py2.py3-none-any.whl
Collecting PyYAML>=3.0 (from amazon-dash)
  HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement PyYAML>=3.0 from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from amazon-dash) because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement PyYAML>=3.0 from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from amazon-dash) because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
```

**Comment by Nekmo** [comment]
It may have been a temporary technical failure of Pip. Try again.

https://status.python.org/

**Comment by djryan012** [comment]
Looking over at PyYaml page there is a issue with reference to 4.1 and since Amazon Dash install is looking for >3.0 it is erroring out.  https://github.com/yaml/pyyaml/issues/203.
Shouldnt I have Yaml already installed from Hassbian (HomeAssistant)?

**Comment by Nekmo** [comment]
You can install the dependency manually:

```
pip3 install pyyaml==3.13
```

Pip will not install the latest version available of pyyaml for Amazon-dash if a version is already installed on your system. It seems to be a temporary problem of the PyYaml project but thanks for the notice.

**Comment by newbyp** [comment]
Hi,

I have the same issue and I have tried 
pip3 install pyyaml==3.13

but I get access is denied. Is it ok for me to do a $ sudo pip3 install pyyaml==3.13

I am running hassbian on a RPI3b+

Sorry but I am a total noob 

Paul.

**Comment by Nekmo** [comment]
You must install the package in the same environment as Amazon-dash. If you have installed Amazon-dash using ``sudo pip install amazon-dash``  you must install the dependency using ``sudo pip install pyyaml==3.13``

Sorry for the inconveniences. This is a problem of the PyYaml project.

**Comment by newbyp** [comment]
Thanks I’ll try again tomorrow.

**Comment by Nekmo** [comment]
Please, can you try again? It seems that the pyyaml project has fixed this problem.

**Comment by newbyp** [comment]
Hi,

Thanks, but I think my lack of understanding is part of the problem. I have tried running 
sudo pip install amazon-dash but it doesn't run as I don't have sudo privs, so I tried pip install amazon-dash and it appears to work, however I then cant run the python -m amazon_dash.install, as it says no module installed. 

I know that hassbian is installed in a virtual environment, but I don't know how toinstall it in that environment. I log in as pi.

I'm sure its my lack of knowledge but I can't seem to install it.

Regards

Paul.

**Comment by djryan012** [comment]
PyYaml project is back up and running and original issue is not resolved. I am having an issue with amazondash not finding config file in /etc folder
```
amazon-pi@hassbian:/ $ amazon-dash --config amazon-dash.yml
Welcome to Amazon-dash v1.1.0 using Python 3.5.3
Listening for events. Amazon-dash will execute the events associated with the registered buttons.
[Error] Amazon Dash Exception (ConfigFileNotFoundError):
The configuration file was not found on "/amazon-dash.yml"

**Comment by Nekmo** [comment]
Check your path:

```
amazon-pi@hassbian:*/* $ ...
```

Your terminal is in the root (/) directory.  And Amazon-dash shows the following error:

```
The configuration file was not found on "/amazon-dash.yml"
```

You can solve this problem using for example:

```
amazon-dash --config /etc/amazon-dash.yml
```
