### ISSUE TITLE
HTTPS & Api Password on Homeassistant

### ISSUE THREAD

**Issue by nicomda** [Nekmo/amazon-dash#62]
* amazon-dash version: 1.0.4
* Python version: 2.7.13
* Operating System: Hassbian 4.14.52-v7

### Description

Most of the people using Homeassistant has https enabled and an API password. You should implement entries to be able to configure both things on each dash. In addition would be cool if we could set the port, cause lot of people has an instance of Homeassistant not in the default port.

### What I Did
I modified execute.py but I'm really new on Python, so it's really difficult for me to add the 2 vars and upload fix. Can you fix it?. It's working for me now. 
If the POST is something like
"http**s**://localhost:**8123**/api/events/YOUR_EVENT_NAME**?api_password=YOURPASSWORD**

Thank you for the soft! Is just awesome, really easy to use. Really simple interface 👍

**Comment by Nekmo** [comment]
This is documented, but there is no example of syntax.

* **homeassistant**: send event to Homeassistant. This argument must be the address to the hass server (protocol and
  port are optional. By default http and 8123, respectively).
* **openhab**: send event to OpenHAB. This argument must be the address to the hass server (protocol and
  port are optional. By default http and 8080, respectively).

**Comment by nicomda** [comment]
So fast! But not yet considering the addition of the API password at the end of the post string.
https://localhost:8123/api/events/YOUR_EVENT_NAME**?api_password=YOURPASSWORD**

**Comment by Nekmo** [comment]
You can set your Homeassistant password using the `access` option. This feature is already included in the latest version of Amazon Dash.
http://docs.nekmo.org/amazon-dash/config_file.html#homeassistant-event

The GET parameter `api_password` works like `x-ha-access` header according to the documentation.
https://developers.home-assistant.io/docs/en/external_api_rest.html

However, it is advisable to define the password using the header. The url with the password can be logged into a file, such as a proxy server.

**Comment by manuelgorman** [comment]
When I add the "access" option, amazon-dash stops picking up my dash button press altogether, and shows nothing in the log. If I leave it out, it crashes and restarts after getting a 401 from my HA server.

**Comment by Nekmo** [comment]
@manuelgorman you need to use the `--debug` parameter to see each time you press the button:
http://docs.nekmo.org/amazon-dash/usage.html#manually

**Comment by Nekmo** [comment]
Closed due to inactivity.
