### ISSUE TITLE
how to run at startup ?

### ISSUE THREAD

**Issue by lam560** [Nekmo/amazon-dash#66]
I'm on Debian stretch with home assistant running and I want to set amazon-dash start automatically.

the command :
`sudo systemctl enable amazon-dash`

returns :
`Failed to enable unit: File amazon-dash.service: No such file or directory`

The default installation folder is located at : **/usr/local/lib/python3.5/dist-packages/amazon_dash**
And I had to create the config file here : /home/me/amazon-dash.yml

How to run it automatically at startup please ?

**Comment by Nekmo** [comment]
Hello, have you executed `python -m amazon_dash.install`?

```
$ sudo pip install amazon-dash  # and after:
$ sudo python -m amazon_dash.install
```

**Comment by lam560** [comment]
Yes but there is one error with the second command :

pierre@orangepiplus2e:~$ sudo pip install amazon-dash
Collecting amazon-dash
Requirement already satisfied: PyYAML>=3.0 in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (3.13)
Requirement already satisfied: click-default-group in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.19.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.6.0)
Requirement already satisfied: scapy>=2.4.0; python_version > "3.0" in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (2.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.5/dist-packages (from amazon-dash) (6.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (2018.4.16)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->amazon-dash) (2.7)
Installing collected packages: amazon-dash
Successfully installed amazon-dash-1.1.0

pierre@orangepiplus2e:~$ sudo python -m amazon_dash.install
/usr/bin/python: No module named amazon_dash

**Comment by Nekmo** [comment]
It seems that Amazon-dash was not installed on the correct path. Please check your python version:

```
sudo python -m amazon_dash.install
```

**Comment by lam560** [comment]
```
pierre@orangepiplus2e:~$ sudo python --version
Python 2.7.13
```

**Comment by Nekmo** [comment]
It seems that there is a problem in your Linux distribution. Pip works using Python3 but the python command works using Python2. Try using the "python3" command instead of "python".

**Comment by lam560** [comment]
```
sudo pip3 install amazon-dash
sudo python3 -m amazon_dash.install
```

`Executing all install scripts for Amazon-Dash
[OK] config has been installed successfully
[OK] systemd service has been installed successfully`

thank you for the fast support 👍
