### ISSUE TITLE
Concurrent actions

### ISSUE THREAD

**Issue by etatus** [Nekmo/amazon-dash#67]
* amazon-dash version: 1.0.3
* Python version: 2.7.9
* Operating System: Raspbian (Linux version 4.9.35-v7+)

### Description
I have 2 dash buttons that add different things to google keep, but when I press them at the same time, it seems not to apply the changes (or only one of them). If I press one button and when it finishes press the other, everything works fine.

### What I Did
I use the Google Keep API from here: https://github.com/Nekmo/gkeep

The cmd in amazon-dash yml is: gkeep --auth /etc/auth.txt edit-item xxx.xxx.xxx "Fruit" --uncheck

**Comment by Nekmo** [comment]
Maybe there's a problem with Google Keep, but I'm going to investigate the problem.

**Comment by Nekmo** [comment]
```
(google-keep-tasks) [nekmo@homura ~/Workspace/google-keep-cli] (develop)$ for i in {1..2}; do python ./scripts/gkeep --auth /home/nekmo/auth.txt add-item 160ad95b558.98ec9e3bfxxxxxx "foo$i" --uncheck &  done
[1] 24757
[2] 24758
```
(works fine)

It's not a problem in Google Keep.

**Comment by Nekmo** [comment]
Concurrent execution is broken after confirmations.

**Comment by Nekmo** [comment]
Solved on develop branch. You can install it using:

```
sudo pip install git+https://github.com/Nekmo/amazon-dash.git@develop#egg=amazon-dash
```

Thank you.
