### ISSUE TITLE
Request: Send 'success' to button (green light)

### ISSUE THREAD

**Issue by gohamstergo** [Nekmo/amazon-dash#75]
Don't think I saw this is any of the previous posts...

Would it be possible to send whatever 'success' command needs to be sent back to the button to get the green light, as if the 'order' was successful? No idea if that's something simple or not. But would be a cool little addition I think.

**Comment by Nekmo** [comment]
This is impossible.

The communication between the button and the Amazon servers uses TLS. To modify the response of the server, the Amazon private key is required. It is also not possible to modify the button via hardware without breaking it (the button does not use screws, it is thermally sealed).

You have more information about how Amazon-dash works in the documentation.
http://docs.nekmo.org/amazon-dash/avoid_purchase.html

**Comment by gohamstergo** [comment]
Alrighty. Ya, I know how to avoid a purchase. I was just hoping to fake a green light. But if there isn't a generic response to spoof, then no worries. Thanks for the reply.
