### ISSUE TITLE
Update to support Home Assistant's new authentication system

### ISSUE THREAD

**Issue by bachya** [Nekmo/amazon-dash#81]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with amazon-dash)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

#### Description

With the release of version 0.77, Home Assistant now requires all users to use the built-in authentication system. Although it isn't happening immediately, one side effect is that eventually, the API key concept (which Amazon Dash currently uses) will go away and all "integrated applications" will need to update their flows to use this new system.

Details here: https://developers.home-assistant.io/docs/en/auth_api.html. One thought might be to provide a command-line tool that guides the user through the OAuth process.

The Home Assistant action Amazon Dash isn't in immediate danger, but that day is coming. Want to submit this for consideration now.

Thanks!

**Comment by Nekmo** [comment]
Hello! Thanks for notifying! And sorry for the wait.

 This will be included in the Amazon-dash release (1.3.0). I will update my version of Home Assistant to perform the tests and develop this new feature.

**Comment by Nekmo** [comment]
Fixed on PR #89 (Thanks @bachya ! ).
