### ISSUE TITLE
amazon-dash taking 100% CPU usage

### ISSUE THREAD

**Issue by norey** [Nekmo/amazon-dash#82]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with amazon-dash)

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version:
You are running Amazon-dash v1.1.1 using Python 2.7.15.
This is the latest release
Installation path: /usr/lib/python2.7/site-packages/amazon_dash

* Python version:
Python 2.7.15

* Pip & Setuptools version:
pip 18.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)

* Operating System:
4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64 GNU/Linux

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [x] The `pip install` or `setup install` command has been completed without errors
- [X] The `python -m amazon_dash.install` command has been completed without errors
- [X] The `amazon-dash discovery` command works without errors
- [X] I have created/edited the configuration file
- [X] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                              
 3814 root      20   0  332392 119180  26960 R 100.0   3.0   5:38.59 amazon-dash 
```

amazon-dash hogs the processor
#### What I Did

```
systemctl start amazon-dash
top -n 1
```

**Comment by Nekmo** [comment]
This is duplicated of:

https://github.com/Nekmo/amazon-dash/issues/73
https://github.com/Nekmo/amazon-dash/issues/40

Amazon-dash listens to your network traffic. If you have a lot of traffic Amazon-dash consumes more CPU. The next Amazon-dash release has a patch to improve performance. Please use the development branch or wait for the release of the new release.

```
pip install git+https://github.com/Nekmo/amazon-dash.git@develop#egg=amazon-dash
```

After testing the patch if you still have issues, request the reopening of this ticket.
