### ISSUE TITLE
High CPU usage on Raspberry Pi

### ISSUE THREAD

**Issue by saurabhsharma001** [Nekmo/amazon-dash#84]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version: 1.2.0
* Python version: 2.7.13
* Pip & Setuptools version: 9.0.1, 33.1.1 
* Operating System: Raspbian (latest)

How to get your version: pip install
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [x] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

Upgraded to the latest version of Amazon Dash 1.2.0. The CPU usage is little less than previous version but still it hovers around 40-50%. 
I am using latest Raspbian on Raspberry Pi 3B+. The same raspberry is also running HomeAssistant.
```

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  287 root      20   0   35084  31252   6472 S  70.6  3.3   5:55.02 amazon-dash
  435 homeass+  20   0  472424  88784  16560 S  60.7  9.4   2:35.33 hass
 2025 pi        20   0    8044   3220   2712 R   0.7  0.3   0:01.08 top
   66 root      20   0       0      0      0 S   0.3  0.0   0:02.35 mmcqd/0

```

#### What I Did
Upgrade from 1.1.1 to 1.2.0. The CPU usage came down about 10%.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by saurabhsharma001** [comment]
More samples:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  287 root      20   0   35084  31252   6472 R  44.6  3.3   6:12.50 amazon-dash
  435 homeass+  20   0  472424  88752  16528 S  11.5  9.3   2:41.15 hass
 2025 pi        20   0    8044   3220   2712 R   1.0  0.3   0:01.40 top
  886 pi        20   0   11576   3704   2992 S   0.7  0.4   0:00.95 sshd
  299 avahi     20   0    6436   3116   2764 S   0.3  0.3   0:00.77 avahi-daemon
```

**Comment by Nekmo** [comment]
A CPU usage of 10% in a raspberry pi is a reasonable usage. Amazon-dash sniffs your network traffic. I have improved the filtering rules but there is not much more that can be improved.

A raspberry pi has a very limited hardware and amazon-dash will use more cpu if you have a lot of traffic in your network.

I can not improve CPU consumption any more without more help.

**Comment by majuss** [comment]
Couldn't we write the sniffer in C++ and reduce the CPU drain dramatically?
