### ISSUE TITLE
Configuration file is wrongly edited. 

### ISSUE THREAD

**Issue by zufi110** [Nekmo/amazon-dash#86]
Hi
I am new to Linux and Raspberry Pi, Already installed and run amazon-dash on raspberry pi zero. discovery mode working ok. when I edited my /home/pi/amazon-dash.yml in terminal then after saving it I am getting a lot of error. Is there an easy way to edit this file without terminal? I understand by default its a read only file So it cannot be edited in simple editor. problem now that config file is a mess up. Is there a way to obtain fresh config file without new installation.If anyone can help me please .
from terminal  my config.yml:-
 GNU nano 2.7.4            File: /home/pi/amazon-dash.yml                      

# amazon-dash.yml
# ---------------
settings:
  # On seconds. Minimum time that must pass between pulsations.
  delay: 10
devices:

#       18:74:2E:1E:24:41:
#       name: Duracell
#       url: `https://maker.ifttt.com/trigger/WEMO/with/key/cxxxxxxxxx-xxxxxxxx`
#       method: post

**Comment by zufi110** [comment]
Thanks , issue was syntax. its working now.But I still interested in replacement config.yml file.

**Comment by Nekmo** [comment]
You can use a text editor with support for and use an online validator. Amazon-dash will include support for other formats.
