### ISSUE TITLE
issue with config file

### ISSUE THREAD

**Issue by KonradIT** [Nekmo/amazon-dash#9]
amazon_dash.exceptions.SecurityException: There should be no permissions for other users in the file "amazon-dash.yml". Only root must be able to write to file.

I get this even after setting chmod 700 to the file.

**Comment by Nekmo** [comment]
What is the user who owns the file?

Please execute this and paste the result:
```
ls -lad amazon-dash.yml
```

**Comment by KonradIT** [comment]
4.0K -rwx------ 1 pi pi 115 Nov 27 19:19 amazon-dash.yml

**Comment by Nekmo** [comment]
Change the permissions to root:

```
chown root:root amazon-dash.yml
```

**Comment by Nekmo** [comment]
This error appears for your own safety. The amazon-dash file allows you to execute commands. If a user modifies the file, it could scale permissions.

There is a new version 0.3.0 in development. It already has a battery of tests and is becoming more usable. I can improve the error message if you want.

**Comment by Nekmo** [comment]
The error message has been improved.

```
(amazon-dash) [nekmo@homura ~/Workspace/amazon-dash] (v0.3.0)$ sudo PYTHONPATH=$PWD ~/.virtualenvs/amazon-dash/bin/python scripts/amazon-dash 
[Error] Amazon Dash Exception:
There should be no permissions for other users in the file "/home/nekmo/Workspace/amazon-dash/amazon-dash.yml". Current permissions: nekmo:users 420. Only root must be able to write to file. Run "sudo chmod 660 '/home/nekmo/Workspace/amazon-dash/amazon-dash.yml' && sudo chown root:root '/home/nekmo/Workspace/amazon-dash/amazon-dash.yml'"
```

If you still have problems please reopen the issue. Thanks.
