### ISSUE TITLE
double sometimes triple does action when pressed 

### ISSUE THREAD

**Issue by internetfan420** [Nekmo/amazon-dash#92]
Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with amazon-dash)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Guideline for bug reports
You can delete this section if your report is not a bug

* amazon-dash version:1.3.0
* Python version:2.7
* Pip & Setuptools version:pip 9.0.1 
* Operating System:raspbian stretch jessie

How to get your version:
```
amazon-dash --version
python --version
pip --version
easy_install --version
```

- [x] The `pip install` or `setup install` command has been completed without errors
- [x] The `python -m amazon_dash.install` command has been completed without errors
- [ ] The `amazon-dash discovery` command works without errors
- [x] I have created/edited the configuration file
- [x] *Amazon-dash service* or `amazon-dash --debug run` works 

#### Description

i have a dash button setup to run a service through ifttt to send a text to a friend to cheer her up through out the day but sometimes it will randomly send multiple texts after one press. like two or so.
also i have the same problem with the python scripts i have set up that will tweet out a few things instead of just one tweet.
#OnepressOnetweet ;)

once i figure this bug out I plan on sharing the scripts and writing a tutorial for the community because this is such an awesome project 

#### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Nekmo** [comment]
Hello, you can try to increase the value of the delay option. By default it is 10 seconds. This option prevents it from being executed multiple times.

Regards

**Comment by internetfan420** [comment]
> Hello, you can try to increase the value of the delay option. By default it is 10 seconds. This option prevents it from being executed multiple times.
> 
> Regards

how high should i make the delay option? in your opinion

**Comment by Nekmo** [comment]
@internetfan420 10 seconds is fine. This is the default value. If you have problems, you can try to increase it. Please, if you still have issues after increase the delay time, let me know.

Sorry for the waiting.

**Comment by Nekmo** [comment]
Closed due to inactivity.
